name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup PureScript dependencies
        run: npm i --global purescript@0.15.15 spago@0.93.40 purescm@latest

      - name: Build source
        run: spago build

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

      - name: Run tests
        run: |
          nix-shell --run "./test.sh"
